### ISSUE TITLE
アイキャッチを自動で表示

### ISSUE THREAD

**Issue by kurudrive** [kurudrive/VK-All-in-One-Expansion-Unit#1]
アイキャッチ画像が登録されていたらページ上部に自動で表示する機能

$content に対してフックで挿入。

但し、SNS連携のボタンとかをフックで同じく$content 前に挿入される事があるため優先順位が低くなるように設定する。

アイキャッチ画像を自動挿入するかどうかは、機能自体のオンオフ画面で制御。
デフォルトはオン
マスター設定画面でオンになっている場合、

□ アイキャッチ画像を自動挿入しない

というカスタムフィールドのチェックボックスにチェックを入れると非表示にする。

**Comment by nc30** [comment]
https://github.com/kurudrive/VK-All-in-One-Expansion-Unit/pull/21

**Comment by kurudrive** [comment]
ありがとうございました。
