### ISSUE TITLE
[ SNS ボタン ] 今は全部表示してるが、非表示ページを設定出来るように機能追加

### ISSUE THREAD

**Issue by kurudrive** [kurudrive/VK-All-in-One-Expansion-Unit#113]
* どの投稿タイプで表示するかのチェックボックスをメイン画面に設置する
* BizVektorと同様に表示を除外するページのIDを , 区切りで設定出来るようにする

**Comment by nc30** [comment]
40c15a23f6e9583f9b43e7fc5095b9cd88d959f4
