### ISSUE TITLE
Pocketのボタンを独自のボタンものにする

### ISSUE THREAD

**Issue by kurudrive** [kurudrive/VK-All-in-One-Expansion-Unit#142]
現状公式のソース埋め込みなので、カウントの取得を調べて他のデザインと合わせたものが実現できるHTMLが出力出来るようにする。
※デザイン自体は見直すので、今の段階で他と揃える必要はありません。

**Comment by nc30** [comment]
https://github.com/kurudrive/VK-All-in-One-Expansion-Unit/commit/35936e39ed62a715dfafd4abb57cb8fddd0d26e7
