### ISSUE TITLE
SNSでシェアした時のタイトルを設定出来る機能を実装

### ISSUE THREAD

**Issue by kurudrive** [kurudrive/VK-All-in-One-Expansion-Unit#25]
カスタムフィールドを設定して、そのフィールドに入力があった場合はOGタグやtweetボタンのタイトルが上書きされる機能

**Comment by kurudrive** [comment]
これってどこにあります？
機能としては動作してないみたいですけどまたマージかプルリクしてないですか？

**Comment by nc30** [comment]
b218d81b03890eb40fa8605d2a52ae35a9cb58d2
別ブランチで上げてました　とりあえずマージしてあります

**Comment by kurudrive** [comment]
SNSボタン（tweetボタンなど）を押された時のタイトル名も入力内容があればその内容が反映されるようにしてください。

**Comment by kurudrive** [comment]
ありがとうございました！
