### ISSUE TITLE
BizVektorに実装してある広告挿入機能を追加

### ISSUE THREAD

**Issue by kurudrive** [kurudrive/VK-All-in-One-Expansion-Unit#32]
BizVektorは more の部分と 本文下 だけで、
ExUnitも同じではあるが、
more 欄 本文下欄 それぞれ入力のテキストエリアを２つずつ設定し、
2つ目の入力がある場合は
col-sm-6
とかにして、四角い広告を横に並べられるようにする

**Comment by nc30** [comment]
#60

**Comment by nc30** [comment]
#60

**Comment by kurudrive** [comment]
・オンオフ画面の説明文がアイキャッチと同じになっているので修正してください。
・設定画面（タブの画面）で見出しが「メタキーワード」になっているので修正してください。
・広告はGoogleの広告専用というわけではないので、AdWords／AdSense の表記は
　「広告の挿入」というニュアンスに変更してください。

**Comment by nc30** [comment]
記事に広告を挿入します
