### ISSUE TITLE
固定ページ本文ウィジェットの名称

### ISSUE THREAD

**Issue by kurudrive** [kurudrive/VK-All-in-One-Expansion-Unit#38]
トップページでだけ使用されるわけではないので、
VK_固定ページ本文
に変更してください

**Comment by SaoriMiyazaki** [comment]
なおしました！

**Comment by kurudrive** [comment]
これよくよく考えたらウィジェットで入れた本文にフックでソーシャルボタンとか表示されちゃうね・・・。
このウィジェットで表示した本文からだけremovefilterって効くかな？
普通の固定ページでもSNSボタン消えちゃうかな・・・？

**Comment by SaoriMiyazaki** [comment]
あ…！ほんとうですね…ちょっとやってみます

**Comment by SaoriMiyazaki** [comment]
ちょっとだけやってみたところ全て消えてしまいました…なにかやり方がちがうかもしれません（私の）
