### ISSUE TITLE
[ 子ページインデックス ] 本文から引用して文字をトリミングした時は末尾に ... を表示する

### ISSUE THREAD

**Issue by kurudrive** [kurudrive/VK-All-in-One-Expansion-Unit#54]

**Comment by nc30** [comment]
https://github.com/kurudrive/VK-All-in-One-Expansion-Unit/commit/93a41e9ec4d4d67762ae9d9696569c9ba8b17613

**Comment by kurudrive** [comment]
* 実際に表示した時にタイトルやリンク先が親ページの情報になる。
* 末尾の ... の前に Please feel free to in と表示される。

とりあえず get_the_excerpt() を通過した時点で $post がリセットされているのだと思います。
