### ISSUE TITLE
[ CTA（Call To Action） ] 新規実装

### ISSUE THREAD

**Issue by kurudrive** [kurudrive/VK-All-in-One-Expansion-Unit#63]
※ 実装出来たら単独のブランチで確認しますので、Developにマージしないでください。

## 保存場所

* カスタム投稿タイプ"cta"で保存
* 見出し、本文、リンク先URL（カスタムフィールド）を保存

### メイン設定画面

* 共通で表示するCTAの設定
共通で表示するCTAを選択してください
 →  プルダウンでカスタム投稿タイプ cta に登録されている投稿を選択。

* CTA機能を使用する投稿タイプ毎にプルダウン

### 各投稿画面

* プルダウンでカスタム投稿タイプ cta に登録されている投稿を選択。
* 未選択だったら、メイン設定画面で設定された デフォルトで表示する cta の投稿を表示
* プルダウンの中に「CTAを表示しない」という項目を含める

### CTAの前に表示するもの

* 子ページインデックス
* SNSボタン

### CTAの後に表示するもの

* 関連記事

**Comment by nc30** [comment]
https://github.com/kurudrive/VK-All-in-One-Expansion-Unit/tree/cta

**Comment by kurudrive** [comment]
公開しました。ありがとうございます。
