### ISSUE TITLE
[ お問い合わせBox ] 新規実装

### ISSUE THREAD

**Issue by kurudrive** [kurudrive/VK-All-in-One-Expansion-Unit#73]
BizVektorの固定ページの下に表示される電話番号と問い合わせボタンのセットのアイテム。
contentにフックする
子ページインデックス同様に、各固定ページの編集画面のメタボックスのチェックボックスを追加して、チェックが入っていたら表示する。
表示順は子ページインデックスの後。

### 入力項目

* 一言メッセージ
* 電話番号
* 電話受付時間
* 問い合わせボタンのリンク先URL
* 問い合わせボタンの文言１（大きめの文字）
* 問い合わせボタンの文言２（小さい文字。入力されない場合もある。）

**Comment by nc30** [comment]
2e8f1af4955c6fbf555cec8762e4392c0440c93d
