### ISSUE TITLE
Favicon、スマホのデスクトップアイコン登録・表示機能

### ISSUE THREAD

**Issue by kurudrive** [kurudrive/VK-All-in-One-Expansion-Unit#8]
BizVektorと同じような仕様でOK

Favicon/スマホのデスクトップアイコンは機能としてはそれぞれ２つだが、マスター設定では一つでOK。

画像の登録がなかったら出力しなくて良いだけなので。

**Comment by nc30** [comment]
https://github.com/kurudrive/VK-All-in-One-Expansion-Unit/commit/2c99234da19012f426a6e31d94c9eb7ebed29322
