### ISSUE TITLE
[ 子ページリストウィジェット ]

### ISSUE THREAD

**Issue by kurudrive** [kurudrive/VK-All-in-One-Expansion-Unit#82]
サイドバー用で固定ページで今いる固定ページの親階層からの子ページリストを表示する。

/plugins/other_widget/old/widget-child-page-list.php と同じ機能。

**Comment by nc30** [comment]
https://github.com/kurudrive/VK-All-in-One-Expansion-Unit/commit/69d5d422a712c8f713e25d8592c3d3a960856ff0
