### ISSUE TITLE
[ admin bar ] ExUnitのメイン設定画面へのリンクメニューを追加する

### ISSUE THREAD

**Issue by kurudrive** [kurudrive/VK-All-in-One-Expansion-Unit#83]

**Comment by kurudrive** [comment]
admin bar の サイト名の右 / 更新の前 あたりの順番に

* vkExUnit_get_little_short_name().' '. _('ActiveSetting','vkExUnit')
  - メイン設定
  - cssカスタマイズ

メニューリンクを追加
権限はテーマオプションが触れるユーザー

**Comment by nc30** [comment]
924baba4154e0e4bff6d75413aa25a08737e4e2e
