### ISSUE TITLE
[ サイドバー用問い合わせボタンウィジェット ] 

### ISSUE THREAD

**Issue by kurudrive** [kurudrive/VK-All-in-One-Expansion-Unit#86]
ページ下部に挿入している問い合わせ情報のボタンをウィジェットとしてサイドバーに問い合わせボタンを設定出来るようにする。

**Comment by nc30** [comment]
aa599af76026af6fc4f46c98c508df6f6e89989d

**Comment by kurudrive** [comment]
サイドバーで表示が崩れるので要修正

**Comment by kurudrive** [comment]
サイドバーで表示が崩れる点についてどうしたら良いと思うか仕様を検討して箇条書きにしてください。
その他エンドユーザーにリリースするにあたって今村さん意外で対応が必要な箇所（デザイン調整など）があれば記載して引き継いでください。
