### ISSUE TITLE
[Child page index] oEmbed埋め込みができない

### ISSUE THREAD

**Issue by hinaloe** [kurudrive/VK-All-in-One-Expansion-Unit#89]
おそらく`renove_filter`で`wpautop`を無効化して独自整形いるためか、ツイート埋め込みなどのoEmbedが使えなくなっている。

**Comment by SaoriMiyazaki** [comment]
> ツイート埋め込みなどのoEmbedが使えなくなっている。

確認してみました。一覧表示した場合の子ページ情報ボックス内は本文より120文字を抜粋して表示しているため、埋め込み表示は行えませんが、子ページ一覧を表示している固定ページ自体の本文には埋め込み表示が行えているようです。

ページ自体の本文内で埋め込み表示ができていないということはございますか？

**Comment by hinaloe** [comment]
posttype=postの投稿本文で発生しました。（固定ページでは確認していません）

テーマ:Lightning

(なお投稿一覧のアーカイブページにも埋め込みの本文は反映されています)

2015年8月24日(月) 11:22 SaoriMiyazaki <notifications@github.com>:

**Comment by kurudrive** [comment]
子ページインデックスは固定ページでしか埋め込み用のチェックボックスが表示されないはずですが、もしかして他の機能の事でしょうか？

**Comment by hinaloe** [comment]
わかりにくくてすいません。子ページインデックスの記事ごとの個別設定に関わらず、この機能を有効化していると全ての投稿タイプにおいて発生するようです。原因としてはoEmbedのフィルターより先に`wpautop`をしてしまっているため。

`remove_filter('the_content','wpautop');`をせずに`add_filter('the_content', 'vkExUnit_show_childPageIndex', 7);`のタイミングを少し落とすことで対応できそうな気がするのですが気のせいでしょうか(その場合他のプラグインとの兼ね合いがありますか…)

**Comment by hinaloe** [comment]
ところでoEmbedとは

- URLを投稿内に一行で入力しておけば自動的に埋め込み形式に変換されて表示される機能

ですが誤解は無いですよね？

**Comment by kurudrive** [comment]
ありがとうございます。修正版をアップいたしました。

**Comment by hinaloe** [comment]
対応ありがとうございます。動作確認をしてみたところ、子ページリスト、サイトマップ共に最終行にoEmbed用ののURLを貼りその後に改行をせずに終了していると正常に動作しなくなることが判明しました。

- 子ページリスト：oEmbedは表示されるが子ページリストは表示されない
- サイトマップ：最終行のoEmbedが変換されない

(いずれもショートコードを利用しているようですが(実装は違うみたいだけど)間に改行がないためと思われます…とは言え最終行が改行の場合は…等ありますがｒｙ)

**Comment by kurudrive** [comment]
Oh...
ありがとうございます...orz
対策検討します。

**Comment by kurudrive** [comment]
@hinaloe さん

大変お待たせしました。修正版アップしました。
