### ISSUE TITLE
初回保存時にすべての機能が有効になる

### ISSUE THREAD

**Issue by ShinichiNishikawa** [kurudrive/VK-All-in-One-Expansion-Unit#91]
1度起こっただけなのでちゃんと検証できていないのですが、VK All in One Expansion Unitをインストールしてからwp-admin/admin.php?page=vkExUnit_setting_pageを最初に保存するとすべてにチェックが入った状態になりました。

**Comment by kurudrive** [comment]
報告ありがとうございます。
現在ウチのイマムラさんが頭を抱えて頑張っております（汗）
近日中に修正出来ると思います。

**Comment by nc30** [comment]
https://github.com/kurudrive/VK-All-in-One-Expansion-Unit/commit/6ba8f2e3e5335d2742bbf676910d0771ca5f84ea
どうも原因がよくわかりませんでしたが、対策しました

**Comment by kurudrive** [comment]
@ShinichiNishikawa さん
対策したようです（・ｗ・；

**Comment by ShinichiNishikawa** [comment]
@nc30 さん、 @kurudrive さん、ありがとうございます：）
これ、めっちゃ便利ですね。ありがたく使わせて頂いております。

**Comment by kurudrive** [comment]
@ShinichiNishikawa さん
ありがとうございます。
今の状態だとLightning以外だと表示が崩れやすかったりして、ウィジェット関連のマークアップやCSSを見なおしてます。
なので、自分でExUnitの部分のCSSを書くと、もしかしたら0.3系までのバージョンアップでclass名やマークアップが変わって表示が崩れてしまうかもしれませんので、CSSでごにょごにょするのは今しばらくお待ちください〜。
他は順次機能追加や使いやすさの改善を行っていきますので、何卒よろしくお願いいたします〜。
