### ISSUE TITLE
[ 関連記事 ] ロジック変更

### ISSUE THREAD

**Issue by kurudrive** [kurudrive/VK-All-in-One-Expansion-Unit#92]
### 現在

現在は同じタグを含んでいる投稿を全て取得している

### 変更後

* カテゴリーとタグ全てが同じ（含んでいる）投稿を取得
* 規定件数に満たない場合は、カテゴリーと一つのタグが同じ投稿を取得
* それでも規定件数に満たない場合はタグが同じ投稿を取得

**Comment by kurudrive** [comment]
ちょっとまった。

**Comment by kurudrive** [comment]
### 現在

現在は同じタグを含んでいる投稿を全て取得している

### 変更後

* タグ全てが同じ（含んでいる）投稿を取得
* 規定件数に満たない場合は、同じタグを含んでいる投稿を全て取得

**Comment by kurudrive** [comment]
ありがとうございます。

**Comment by kurudrive** [comment]
@nc30 
実装したら確認してください。

**Comment by kurudrive** [comment]
* 今の記事に設定されているタグを全て含んでいる他の投稿を取得・表示。  それが１０件に見たない場合
* 今の記事に設定されている一つのタグを含んでいる他の投稿を取得して表示、合計１０件まで表示する

**Comment by nc30** [comment]
2694cc2497b8e5ec7fbe5edf9c06433ea8b4cede
完了です

**Comment by kurudrive** [comment]
* <em>今の記事に設定されているタグを全て含んでいる</em>他の投稿を取得・表示。  それが１０件に満たない場合
* <em>今の記事に設定されているタグを全て含んでいる他の記事の後に</em>今の記事に設定されている一つのタグを含んでいる他の投稿を取得して表示、合計１０件まで表示する

**Comment by nc30** [comment]
そういうこいとは先に言ってください

**Comment by nc30** [comment]
15852e892b682dcdee044b05a385f36e471872b2
