### ISSUE TITLE
[ Page list from ancestor ] 固定ページ下部に先祖ページからのリストを表示する

### ISSUE THREAD

**Issue by ShinichiNishikawa** [kurudrive/VK-All-in-One-Expansion-Unit#93]
子ページ一覧の表示と同じノリで、兄弟ページの一覧が載せられると嬉しい。
親をとってその子どもを並べる感じです。

兄弟関係をうまく見せるのが難しいですけど、分かりやすくできるといいなぁ、と思います。

**Comment by kurudrive** [comment]
@ShinichiNishikawa さん

たぶんBizVektorでいうところの
http://bizvektor.com/setting/wpsetting/applicationserver/
の下に表示されてるような感じですよね？

**Comment by ShinichiNishikawa** [comment]
おー、構造ごと見せちゃうっていうのもいいですね。
@kurudrive

**Comment by kurudrive** [comment]
@SaoriMiyazaki さん

デザインがちょっと要調整ですな...

**Comment by kurudrive** [comment]
@ShinichiNishikawa さん
3.7.0 でリリースしましたー。
機能をONにしてみてみてくださいね〜。
|彡 ｻｯ!
