### ISSUE TITLE
[ 新着記事ウィジェット ] 表示フォーマットを増やす

### ISSUE THREAD

**Issue by kurudrive** [kurudrive/VK-All-in-One-Expansion-Unit#97]
現状は

「サムネイル / タイトル / 日付」

を表示しているが、

企業サイトでよくある

「日付 / カテゴリー / タイトル」

の形式で表示出来るようにする。

### ウィジェットの設定項目

レイアウトを変更出来るように

[ 表示項目 ]
* サムネイル画像 / 記事タイトル / 公開日
* 公開日 / カテゴリー/ 記事タイトル

をラジオボタンで選択出来るように（デフォルトはサムネイル付き）

### カテゴリーの表示について

一つの投稿に複数のカテゴリーが割り当てられていたら、とりあえずBizVektorと同じく全てのカテゴリーを表示するようにしてください。

HTMLやCSSは後で調整します。

**Comment by nc30** [comment]
acedc132c485df085f33eb15e23f0486a8982107

**Comment by nc30** [comment]
92行目でhtmlを修正できます
